#!/usr/bin/env bash

################################################## ####################
# @author: Linus Fernandes (linusfernandes@gmail.com)
# @file: gitmerge
# @created: Wednesday Feb 19, 2020 21:59:57 IST
# @copyright: Copyright (c) Linus Fernandes
# @description: 
################################################## ####################
RED = "\ 033 [0; 31m"
NC = "\ 033 [0m" # No Color
set -e
command = ""
EXIT message trap
function message ()
{
  ret = $?
  if [$ ret -eq 0]
  Then
    echo exit $ ret from last command: $ command
  else
    echo $ {RED} exit $ ret from last command: $ command $ {NC}
fi
  exit $ ret
}
command = "git checkout master"
command $
command = "git pull"
command $
command = "git checkout development"
command $
command = "git merge master"
command $
command = "gitpush"
command $
