#!/usr/bin/env bash
curl -X POST -H "Content-Type: application/json" -d '{ "title": "JS: Node Tutorial #1", "description":"Tutorial #3 Description" }' http://localhost:8080/api/tutorials
curl -X POST -H "Content-Type: application/json" -d '{ "title": "JS: Node Tutorial #2", "description":"Tutorial #2 Description" }' http://localhost:8080/api/tutorials
curl -X POST -H "Content-Type: application/json" -d '{ "title": "JS: Vue Tutorial #3", "description":"Tutorial #3 Description" }' http://localhost:8080/api/tutorials
curl -X POST -H "Content-Type: application/json" -d '{ "title": "JS: React Tutorial #3", "description":"Tutorial #4 Description" }' http://localhost:8080/api/tutorials
curl -X POST -H "Content-Type: application/json" -d '{ "title": "JS: Angular Tutorial #3", "description":"Tutorial #5 Description" }' http://localhost:8080/api/tutorials
